version: "3"

services:
  brainyboat-autopilot:
    build: "."
    restart: "always"

    environment:
      - BASE_URL=${BASE_URL}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - IMAI=${IMAI}
    
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0

volumes:
  brainyboat-database: